# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_faba_wrappers", use_symbols = TRUE, package_name = "faba")

#' @usage NULL
#' @useDynLib faba, .registration = TRUE
NULL

#' Sift through BAM records to identify potential variant sites.  The
#' resulting sites may not be necessarily true hits, but they can
#' form a good starting candidate pool.  Later, routines in
#' `aggregate` could revisit them all, regardless of significance
#' levels, and collect sufficient statistics for further tests.  So,
#' we just need to return a vector of (chr: Box<str>, lb: i64, ub:
#' i64)
#'
#' @export
compare_case_control_bam <- function(fg_bam, bg_bam, block_size) .Call(wrap__compare_case_control_bam, fg_bam, bg_bam, block_size)


# nolint end
